#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
import logging
import os

from pathlib import Path

from dotenv import load_dotenv

from globalroamer_ai.lib.app_config import load_yaml_config
from globalroamer_ai.lib.setup_logger import setup_logger

from globalroamer_ai.lib.ai_summary_service import AISummaryService
from globalroamer_ai.lib.root_cause_service import RootCauseService
from globalroamer_ai.lib.retry_advisor import RetryAdvisor
from globalroamer_ai.lib.campaign_health import CampaignHealthScorer
from globalroamer_ai.lib.report_writer import ReportWriter

from globalroamer_ai.lib.exceptions import GlobalRoamerAIException

load_dotenv()

logger = logging.getLogger("report_main")


def load_chunks(chunks_dir: str) -> list:
    """
    Load all chunk JSON files from chunks directory.
    """

    chunks = []

    chunk_files = sorted(
        Path(chunks_dir).glob("*_chunks.json")
    )

    logger.info(
        f"Discovered {len(chunk_files)} chunk files"
    )

    for chunk_file in chunk_files:
        logger.info(f"Loading chunks: {chunk_file}")

        with open(chunk_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, list):
            chunks.extend(data)

    logger.info(
        f"Loaded {len(chunks)} chunks"
    )

    return chunks


def load_similarity_results(ai_summary_dir: str) -> dict:
    """
    Load similarity results generated by analyze_main.py.

    Returns:
        {
            chunk_id: [similarity_result, ...]
        }
    """

    similarity_dir = Path(ai_summary_dir) / "similarity_results"

    results_by_chunk = {}

    if not similarity_dir.exists():
        logger.warning(
            f"Similarity results directory does not exist: {similarity_dir}"
        )
        return results_by_chunk

    result_files = sorted(
        similarity_dir.glob("*_similarity.json")
    )

    logger.info(
        f"Discovered {len(result_files)} similarity result files"
    )

    for result_file in result_files:
        logger.info(
            f"Loading similarity result: {result_file}"
        )

        with open(result_file, "r", encoding="utf-8") as f:
            results = json.load(f)

        if not results:
            continue

        chunk_id = results[0].get("chunk_id")

        # Important:
        # The first result may be the same chunk itself.
        # We keep the full list for now, but this can be filtered later.
        if chunk_id:
            results_by_chunk[chunk_id] = results

    logger.info(
        f"Loaded similarity results for "
        f"{len(results_by_chunk)} chunks"
    )

    return results_by_chunk


def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--config-dir",
        required=True,
        help="Path to config directory"
    )

    args = parser.parse_args()

    # -----------------------------------------------------
    # Config
    # -----------------------------------------------------

    cfg = load_yaml_config(
        args.config_dir
    )

    # -----------------------------------------------------
    # Logger
    # -----------------------------------------------------

    logfile = os.path.join(
        cfg.log_dir,
        "report.log"
    )

    setup_logger(logfile)

    logger.info(
        "=== GlobalRoamer AI Report Started ==="
    )

    try:

        # -------------------------------------------------
        # Load chunks and similarity results
        # -------------------------------------------------

        chunks = load_chunks(
            cfg.chunks_dir
        )

        if not chunks:
            logger.warning(
                "No chunks available for report generation"
            )
            return

        similarity_results_by_chunk = load_similarity_results(
            cfg.ai_summary_dir
        )

        # -------------------------------------------------
        # Services
        # -------------------------------------------------

        summary_service = AISummaryService(
            model=cfg.llm_model
        )

        root_cause_service = RootCauseService(
            model=cfg.llm_model
        )

        retry_advisor = RetryAdvisor()

        health_scorer = CampaignHealthScorer()

        report_writer = ReportWriter(
            ai_summary_dir=cfg.ai_summary_dir,
            root_cause_dir=cfg.root_cause_dir,
            campaign_health_dir=cfg.campaign_health_dir
        )

        # -------------------------------------------------
        # Generate summaries
        # -------------------------------------------------

        summaries = summary_service.summarize_many(
            chunks=chunks,
            similarity_results_by_chunk=similarity_results_by_chunk
        )

        # -------------------------------------------------
        # Generate root-cause reports
        # -------------------------------------------------

        root_cause_reports = root_cause_service.analyze_many(
            chunks=chunks,
            similarity_results_by_chunk=similarity_results_by_chunk
        )

        # -------------------------------------------------
        # Generate retry recommendations
        # -------------------------------------------------

        retry_reports = []

        for chunk in chunks:
            similar_incidents = similarity_results_by_chunk.get(
                chunk.get("chunk_id"),
                []
            )

            retry_report = retry_advisor.analyze_retry_strategy(
                chunk=chunk,
                similar_incidents=similar_incidents
            )

            retry_reports.append(retry_report)

        # -------------------------------------------------
        # Campaign health
        # -------------------------------------------------

        health_report = health_scorer.score_campaign(
            chunks=chunks,
            retry_reports=retry_reports,
            root_cause_reports=root_cause_reports
        )

        # -------------------------------------------------
        # Write reports
        # -------------------------------------------------

        report_writer.write_ai_summaries(
            summaries=summaries
        )

        report_writer.write_root_cause_reports(
            reports=root_cause_reports
        )

        report_writer.write_campaign_health(
            health_report=health_report
        )

        report_writer.write_full_report(
            summaries=summaries,
            root_cause_reports=root_cause_reports,
            retry_reports=retry_reports,
            health_report=health_report
        )

        logger.info(
            "=== GlobalRoamer AI Report Finished ==="
        )

    except GlobalRoamerAIException as e:

        logger.error(
            f"Application error: {e}"
        )

        raise

    except Exception as e:

        logger.exception(
            f"Unexpected fatal error: {e}"
        )

        raise


if __name__ == "__main__":
    main()
